# manifest file for argocd dashboard certificate
# certificate.yml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dashboard-certificate
  namespace: argocd
spec:
  commonName: argocd.superfast-delivery.yashraj-jaiswal.site
  secretName: argocd.superfast-delivery.yashraj-jaiswal.site
  dnsNames:
    - argocd.superfast-delivery.yashraj-jaiswal.site
  issuerRef:
    name: traefik-letsencrypt-staging
    kind: ClusterIssuer
