apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: traefik-letsencrypt-prod
spec:
  acme:
    email: yashraj6370@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: traefik-cert-manager-clusterissuer-prod-key
    solvers:
      - dns01:
          route53:
            region: "us-east-1"
