# values for traefik helm installation
# values.yml
service:
  enabled: true
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    external-dns.alpha.kubernetes.io/hostname: "*.superfast-delivery.yashraj-jaiswal.site"

providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
    allowExternalNameServices: false
    namespaces: []
  kubernetesIngress:
    enabled: true
    allowExternalNameServices: false
    allowEmptyServices: false
    publishedService:
      enabled: false

additionalArguments:
  - --api.dashboard=true
  - --api.insecure=false
  - --accesslog=true
  - --accesslog.format=json
  - --accesslog.fields.headers.defaultmode=keep

ports:
  websecure:
    tls:
      enabled: true

externalTrafficPolicy: Local

persistence:
  enabled: true
  name: data
  storageClass: "gp3"
  accessMode: ReadWriteOnce
  size: 128Mi
  path: /data
