# manifest file for headlamp dashboard certificate
# certificate.yml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dashboard-certificate
  namespace: headlamp
spec:
  commonName: headlamp.superfast-delivery.yashraj-jaiswal.site
  secretName: headlamp.superfast-delivery.yashraj-jaiswal.site
  dnsNames:
    - headlamp.superfast-delivery.yashraj-jaiswal.site
  issuerRef:
    name: traefik-letsencrypt-staging
    kind: ClusterIssuer
