apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dashboard-certificate
  namespace: argocd
spec:
  commonName: argocd.superfast-delivery.yashraj-jaiswal.site
  secretName: argocd.superfast-delivery.yashraj-jaiswal.site
  dnsNames:
    - argocd.superfast-delivery.yashraj-jaiswal.site
  issuerRef:
    name: traefik-letsencrypt-staging
    kind: ClusterIssuer

---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: dashboard-transport
  namespace: argocd
spec:
  insecureSkipVerify: true

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dashboard-ingressroute
  namespace: argocd
spec:
  entryPoints: [websecure]
  routes:
    - kind: Rule
      match: Host(`argocd.superfast-delivery.yashraj-jaiswal.site`)
      services:
        - kind: Service
          name: argocd-server
          port: 443
          serversTransport: dashboard-transport
  tls:
    secretName: argocd.superfast-delivery.yashraj-jaiswal.site
