apiVersion: v1
kind: ServiceAccount
metadata:
  name: headlamp-admin
  namespace: headlamp

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: headlamp-admin
subjects:
  - kind: ServiceAccount
    name: headlamp-admin
    namespace: headlamp
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Secret
metadata:
  name: headlamp-admin-token
  namespace: headlamp
  annotations:
    kubernetes.io/service-account.name: "headlamp-admin"
type: kubernetes.io/service-account-token

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dashboard-certificate
  namespace: headlamp
spec:
  commonName: headlamp.superfast-delivery.yashraj-jaiswal.site
  secretName: headlamp.superfast-delivery.yashraj-jaiswal.site
  dnsNames:
    - headlamp.superfast-delivery.yashraj-jaiswal.site
  issuerRef:
    name: traefik-letsencrypt-staging
    kind: ClusterIssuer

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dashboard-ingressroute
  namespace: headlamp
spec:
  entryPoints: [websecure]
  routes:
    - kind: Rule
      match: Host(`headlamp.superfast-delivery.yashraj-jaiswal.site`)
      services:
        - kind: Service
          name: headlamp
          port: 80
          scheme: http
  tls:
    secretName: headlamp.superfast-delivery.yashraj-jaiswal.site
